# Generated by Django 3.0.3 on 2020-02-22 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Allergy & Immunology', 'Allergy & Clinical Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Business of Medicine', 'Business of Medicine'), ('Cardiology', 'Cardiology'), ('Critical Care', 'Critical Care'), ('Dermatology', 'Dermatology'), ('Diabetes & Endocrinology', 'Diabetes & Endocrinology'), ('Emergency Medicine', 'Emergency Medicine'), ('Family Medicine', 'Family Medicine'), ('Gastroenterology', 'Gastroenterology')], default='theory', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('finished', 'Finished')], default='new', max_length=20)),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
