# Generated by Django 3.0.3 on 2020-02-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearning', '0003_auto_20200228_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('finished', 'Finished')], default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='ArticleInstance',
        ),
    ]
