# Generated by Django 3.0.3 on 2020-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearning', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('allergy-immunology', 'Allergy & Clinical Immunology'), ('anesthesiology', 'Anesthesiology'), ('businessmedicine', 'Business of Medicine'), ('cardiology', 'Cardiology'), ('criticalcare', 'Critical Care'), ('dermatology', 'Dermatology'), ('diabetes-endocrinology', 'Diabetes & Endocrinology'), ('emergencymedicine', 'Emergency Medicine'), ('familymedicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('generalsurgery', 'General Surgery'), ('oncology', 'Oncology'), ('hiv', 'HIV/AIDS'), ('hospitalmedicine', 'Hospital Medicine'), ('infectiousdiseases', 'Infectious Diseases'), ('internalmedicine', 'Internal Medicine'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('womenshealth', "Ob/Gyn & Women's Health"), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pathology', 'Pathology & Lab Medicine'), ('pediatrics', 'Pediatrics'), ('plastic-surgery', 'Plastic Surgery'), ('psychiatry', 'Psychiatry'), ('publichealth', 'Public Health & Prevention'), ('pulmonarymedicine', 'Pulmonary Medicine'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('transplantation', 'Transplantation'), ('urology', 'Urology')], default='theory', max_length=50),
        ),
    ]
