# Generated by Django 3.0.3 on 2020-03-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearning', '0007_auto_20200315_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_med',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('type', 'id_med', 'slug'), name='unique_article'),
        ),
    ]
