# Generated by Django 3.0.3 on 2020-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearning', '0008_auto_20200315_1901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='unique_article',
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('type', 'id_med'), name='unique_article'),
        ),
    ]
