# Generated by Django 3.0.4 on 2020-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlearning', '0010_auto_20200322_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
